# Generated by Django 3.0.6 on 2020-12-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizJuegos',
            fields=[
                ('juego', models.OneToOneField(db_column='id_juego', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Juego', verbose_name='Identificador del juego')),
                ('vector_genero', models.CharField(max_length=256)),
                ('vector_plataforma', models.CharField(max_length=256)),
                ('cpu0', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu1', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu2', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu3', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu4', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu5', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu6', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu7', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu8', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu9', models.PositiveIntegerField(blank=True, default=0)),
                ('cde0', models.PositiveIntegerField(blank=True, default=0)),
                ('cde1', models.PositiveIntegerField(blank=True, default=0)),
                ('cde2', models.PositiveIntegerField(blank=True, default=0)),
                ('cde3', models.PositiveIntegerField(blank=True, default=0)),
                ('cde4', models.PositiveIntegerField(blank=True, default=0)),
                ('cde5', models.PositiveIntegerField(blank=True, default=0)),
                ('cde6', models.PositiveIntegerField(blank=True, default=0)),
                ('cde7', models.PositiveIntegerField(blank=True, default=0)),
                ('cde8', models.PositiveIntegerField(blank=True, default=0)),
                ('cde9', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TfIdf',
            fields=[
                ('juego', models.OneToOneField(db_column='id_juego', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Juego', verbose_name='Identificador del juego')),
                ('vector', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MatrizPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_genero', models.CharField(max_length=256)),
                ('vector_plataforma', models.CharField(max_length=256)),
                ('cpu0', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu1', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu2', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu3', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu4', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu5', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu6', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu7', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu8', models.PositiveIntegerField(blank=True, default=0)),
                ('cpu9', models.PositiveIntegerField(blank=True, default=0)),
                ('cde0', models.PositiveIntegerField(blank=True, default=0)),
                ('cde1', models.PositiveIntegerField(blank=True, default=0)),
                ('cde2', models.PositiveIntegerField(blank=True, default=0)),
                ('cde3', models.PositiveIntegerField(blank=True, default=0)),
                ('cde4', models.PositiveIntegerField(blank=True, default=0)),
                ('cde5', models.PositiveIntegerField(blank=True, default=0)),
                ('cde6', models.PositiveIntegerField(blank=True, default=0)),
                ('cde7', models.PositiveIntegerField(blank=True, default=0)),
                ('cde8', models.PositiveIntegerField(blank=True, default=0)),
                ('cde9', models.PositiveIntegerField(blank=True, default=0)),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.CASCADE, related_name='juego', to='sjug.Juego', verbose_name='Juego al que pertenece la matriz')),
                ('jugador', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='sjug.Usuario', verbose_name='Identificador del usuario')),
            ],
        ),
    ]
