# Generated by Django 3.0.6 on 2020-12-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
        ('sadm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Usuario', verbose_name='Identificador del administrador')),
                ('nombre', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
