# Generated by Django 3.1.4 on 2020-12-28 18:02

from django.db import migrations, models
import django.db.models.deletion
import gamehouse.sadm.models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0002_auto_20201228_1802'),
        ('sadm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tf_idf',
            fields=[
                ('juego', models.OneToOneField(db_column='id_juego', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.juego', verbose_name='Identificador del juego')),
                ('vector', models.FilePathField(path=gamehouse.sadm.models.tf_idf_path)),
            ],
        ),
        migrations.RenameField(
            model_name='matrizjuegos',
            old_name='vectorCDE',
            new_name='vector_cde',
        ),
        migrations.RenameField(
            model_name='matrizjuegos',
            old_name='vectorCPU',
            new_name='vector_cpu',
        ),
        migrations.RenameField(
            model_name='matrizjuegos',
            old_name='vectorGENERO',
            new_name='vector_genero',
        ),
        migrations.RenameField(
            model_name='matrizjuegos',
            old_name='vectorPLATAFORMA',
            new_name='vector_plataforma',
        ),
        migrations.RemoveField(
            model_name='matrizjuegos',
            name='agno',
        ),
        migrations.DeleteModel(
            name='TfIdf',
        ),
    ]
