# Generated by Django 3.0.6 on 2020-12-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='nombre',
            new_name='administador',
        ),
    ]
