# Generated by Django 3.1.4 on 2020-12-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0002_auto_20201228_1802'),
        ('sadm', '0002_auto_20201228_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf_idf',
            name='juego',
            field=models.OneToOneField(db_column='juego', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.juego', verbose_name='Identificador del juego'),
        ),
    ]
