# Generated by Django 3.0.6 on 2020-12-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadm', '0002_auto_20201223_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='administador',
            new_name='nombre',
        ),
    ]
