# Generated by Django 3.0.6 on 2020-12-22 15:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id_compania', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaniasAsociadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='juegos_asociados', to='sjug.Compania', verbose_name='Compañias que hicieron el juego')),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id_generacion', models.AutoField(primary_key=True, serialize=False)),
                ('generacion', models.CharField(max_length=20, unique=True, verbose_name='Numero de generacion')),
                ('bits', models.PositiveIntegerField(blank=True, default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2056)])),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenerosAsociados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.CASCADE, related_name='juegos_asociados', to='sjug.Genero', verbose_name='Generos que conforman el juego')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField(default=2020)),
                ('descripcion', models.TextField(max_length=5000)),
                ('companias', models.ManyToManyField(through='sjug.CompaniasAsociadas', to='sjug.Compania')),
                ('generos', models.ManyToManyField(through='sjug.GenerosAsociados', to='sjug.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30, verbose_name='El de esta version de recomendacion')),
                ('retroalimentacion', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=254)),
                ('fec_nac', models.DateField(default=datetime.date.today, help_text='Use el formato:DD-MM-AAAA')),
            ],
        ),
        migrations.CreateModel(
            name='Cde',
            fields=[
                ('jugador', models.OneToOneField(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Usuario', verbose_name='Jugador a quien pertenecen las CDE')),
                ('cardes1', models.CharField(max_length=256)),
                ('cardes2', models.CharField(max_length=256)),
                ('cardes3', models.CharField(max_length=256)),
                ('cardes4', models.CharField(max_length=256)),
                ('cardes5', models.CharField(max_length=256)),
                ('cardes6', models.CharField(max_length=256)),
                ('cardes7', models.CharField(max_length=256)),
                ('cardes8', models.CharField(max_length=256)),
                ('cardes9', models.CharField(max_length=256)),
                ('cardes10', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('cpu', models.OneToOneField(db_column='id_cpu', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Usuario', verbose_name='Identificador de CPU')),
                ('carusu1', models.CharField(max_length=256)),
                ('carusu2', models.CharField(max_length=256)),
                ('carusu3', models.CharField(max_length=256)),
                ('carusu4', models.CharField(max_length=256)),
                ('carusu5', models.CharField(max_length=256)),
                ('carusu6', models.CharField(max_length=256)),
                ('carusu7', models.CharField(max_length=256)),
                ('carusu8', models.CharField(max_length=256)),
                ('carusu9', models.CharField(max_length=256)),
                ('carusu10', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.Usuario', verbose_name='Identificador del jugador')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='Nickname del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlataformasAsociadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_asociadas', to='sjug.Juego', verbose_name='Juegos que pertenecen a la plataforma')),
                ('plataforma', models.ForeignKey(db_column='plataforma', on_delete=django.db.models.deletion.CASCADE, related_name='juegos_asociados', to='sjug.Plataforma', verbose_name='Plataforma a las que pertenece el juego')),
            ],
        ),
        migrations.CreateModel(
            name='ListGeneros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listgenero', models.CharField(max_length=100)),
                ('listplataforma', models.CharField(max_length=100)),
                ('juego', models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos_boolean', to='sjug.Juego', verbose_name='generos en boolean')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='El nombre de la lista')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion detallada de la lista si existe')),
                ('juego', models.ManyToManyField(to='sjug.Juego', verbose_name='Juegos que conforman esta lista')),
                ('recomendacion', models.ForeignKey(db_column='id_recomendacion', on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='sjug.Recomendacion', verbose_name='Recomendacion a la que pertenece esta lista')),
            ],
        ),
        migrations.CreateModel(
            name='JuegosFavoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='sjug.Juego', verbose_name='Juego que le gusta al jugador')),
                ('jugador', models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juegos_favoritos', to='sjug.Jugador', to_field='nickname', verbose_name='Jugador al que le gusta el juego')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(through='sjug.PlataformasAsociadas', to='sjug.Plataforma'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.URLField(max_length=511)),
                ('alt', models.CharField(max_length=100, verbose_name='Texto alternativo a la imagen')),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sjug.Juego', verbose_name='Imagenes que representan el juego')),
            ],
        ),
        migrations.CreateModel(
            name='GenerosFavoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(db_column='genero', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='sjug.Genero', verbose_name='Genero que le gusta al jugador')),
                ('jugador', models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos_favoritos', to='sjug.Jugador', to_field='nickname', verbose_name='Jugador al que le gusta el genero')),
            ],
        ),
        migrations.AddField(
            model_name='generosasociados',
            name='juego',
            field=models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos_asociados', to='sjug.Juego', verbose_name='Juegos que pertenecen al genero'),
        ),
        migrations.AddField(
            model_name='companiasasociadas',
            name='juego',
            field=models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companias_asociadas', to='sjug.Juego', verbose_name='Juegos que pertenecen a la plataforma'),
        ),
        migrations.CreateModel(
            name='Vector_Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100)),
                ('cde', models.CharField(max_length=100)),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='sjug.Juego', verbose_name='Juego al que pertenece la opinion')),
                ('jugador', models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector_caracteristicas', to='sjug.Jugador', to_field='nickname', verbose_name='Creador de la opinion')),
            ],
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='jugador',
            field=models.ForeignKey(db_column='jugador', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='sjug.Jugador', to_field='nickname', verbose_name='Jugador al que se le hace esta recomendacion'),
        ),
        migrations.CreateModel(
            name='PlataformasFavoritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(db_column='plataforma', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='sjug.Plataforma', verbose_name='Plataforma que tiene el jugador')),
                ('jugador', models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_favoritas', to='sjug.Jugador', to_field='nickname', verbose_name='Jugador que tiene la plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('gusto', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guion', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('artes', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('jugabilidad', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tecnico', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='sjug.Juego', verbose_name='Juego al que pertenece la opinion')),
                ('jugador', models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opiniones', to='sjug.Jugador', to_field='nickname', verbose_name='Creador de la opinion')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='generos',
            field=models.ManyToManyField(through='sjug.GenerosFavoritos', to='sjug.Genero'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='juegos',
            field=models.ManyToManyField(through='sjug.JuegosFavoritos', to='sjug.Juego', verbose_name='Juegos favoritos del usuario'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='plataformas',
            field=models.ManyToManyField(through='sjug.PlataformasFavoritas', to='sjug.Plataforma'),
        ),
    ]
