# Generated by Django 3.1.4 on 2020-12-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cde',
            old_name='cardes1',
            new_name='cde0',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes10',
            new_name='cde1',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes2',
            new_name='cde2',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes3',
            new_name='cde3',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes4',
            new_name='cde4',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes5',
            new_name='cde5',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes6',
            new_name='cde6',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes7',
            new_name='cde7',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes8',
            new_name='cde8',
        ),
        migrations.RenameField(
            model_name='cde',
            old_name='cardes9',
            new_name='cde9',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu1',
            new_name='cpu0',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu10',
            new_name='cpu1',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu2',
            new_name='cpu2',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu3',
            new_name='cpu3',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu4',
            new_name='cpu4',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu5',
            new_name='cpu5',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu6',
            new_name='cpu6',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu7',
            new_name='cpu7',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu8',
            new_name='cpu8',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='carusu9',
            new_name='cpu9',
        ),
        migrations.RenameField(
            model_name='vector_caracteristicas',
            old_name='cde',
            new_name='cdes',
        ),
        migrations.RenameField(
            model_name='vector_caracteristicas',
            old_name='cpu',
            new_name='cpus',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='cpu',
        ),
        migrations.AddField(
            model_name='cpu',
            name='jugador',
            field=models.OneToOneField(db_column='jugador', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.jugador', verbose_name='Jugador a quien pertenecen las CPU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cde',
            name='jugador',
            field=models.OneToOneField(db_column='jugador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sjug.jugador', verbose_name='Jugador a quien pertenecen las CDE'),
        ),
        migrations.AlterField(
            model_name='vector_caracteristicas',
            name='jugador',
            field=models.ForeignKey(db_column='jugador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vectores_caracteristicas', to='sjug.jugador', verbose_name='Jugador al que pertenece este vector de caracteristicas'),
        ),
    ]
