# Generated by Django 3.0.6 on 2020-12-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPlataformas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listplataforma', models.CharField(max_length=100)),
                ('juego', models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_boolean', to='sjug.Juego', verbose_name='plataformas en boolean')),
            ],
        ),
        migrations.CreateModel(
            name='ListGeneros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listgenero', models.CharField(max_length=100)),
                ('juego', models.ForeignKey(db_column='juego', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generos_boolean', to='sjug.Juego', verbose_name='generos en boolean')),
            ],
        ),
    ]
