# Generated by Django 3.0.6 on 2020-12-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='agnio',
            new_name='anio',
        ),
    ]
