# Generated by Django 3.0.6 on 2020-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0002_auto_20201220_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='campo_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Representacion slug del titulo'),
        ),
    ]
