"""
Django settings for gamehouse project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y4=v-u4%sib=5lhe$_(3@!8u*ym8*%(7tg$pu_pi95#*qh0%kw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', #Para autenticacion
    'django.contrib.contenttypes', #Para autenticacion
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #.....................#
    #Sistema de jugadores 
    'gamehouse.sjug',
    #Sistema de administradores
    'gamehouse.sadm',
    #.....................#
    # 'multiselectfield',
    #install first:pip install djangorestframework
    #late: pip install django-filter
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', #Manage sessions across requests
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #Associates users with requests using sessions
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gamehouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #directorio templates
        'DIRS': ['%s/templates/' %(BASE_DIR)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gamehouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'gamehouse.db'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#Checar https://stackoverflow.com/questions/4876370/django-date-format-dd-mm-yyyy 
DATE_INPUT_FORMATS = ('%d/%m/%Y','%d-%m-%Y') #('%d-%m-%Y','%Y-%m-%d')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR,
  ('css','%s/css' % STATIC_DIR),
  ('js','%s/js' % STATIC_DIR),
 #('bootstrap','%s/bootstrap-3.1.1-dist/'% (STATIC_DIR)),
 #('jquery','%s/jquery-1-11-1-dist/'% (STATIC_DIR)),
 #('jquery-ui','%s/jquery-ui-1.10.4/'% (STATIC_DIR)), 
]

""" Redireccionamiento automatico """
#https://docs.djangoproject.com/en/3.1/ref/settings/#login-url
LOGIN_REDIRECT_URL = reverse_lazy('dashboard')
LOGIN_URL = '/login'
LOGOUT_REDIRECT_URL = '/'

###
MEDIA_ROOT = STATIC_DIR+'/Raw/'
